### ISSUE TITLE
Using resetTopViewWithAnimations to achieve a bounce effect.

### ISSUE THREAD

**Issue by davisg123** [ECSlidingViewController/ECSlidingViewController#144]
I can't find an example of resetTopViewWithAnimations being used anywhere.  The sample app doesn't use animations, and every forum I've seen doesn't mention how to actually implement animations using this method.  Can someone explain how I would achieve a basic bounce effect (view resets to center and then bounces a few times) by using this?

**Comment by bablu-joshi** [comment]
- (void)anchorTopViewToRightAnimated:(BOOL)animated {
    
    
    [UIView animateWithDuration:1.0 delay:0 usingSpringWithDamping:0.5 initialSpringVelocity:1.0 options:UIViewAnimationOptionCurveLinear animations:^{
        [self anchorTopViewToRightAnimated:NO onComplete:nil];
        
    } completion:^(BOOL finished) {
        
    }];
    
}
