### ISSUE TITLE
Support for mix of portrait/landscape view controllers

### ISSUE THREAD

**Issue by marchv** [ECSlidingViewController/ECSlidingViewController#211]
Hi :)

I have a number of view controllers set up to use ECSlidingViewController. But I would like some of them to support portrait mode only and some of them to support both portrait/landscape mode.

I've managed to set the
– shouldAutorotate
– supportedInterfaceOrientations
of the view controllers. But if I go from one landscape mode view controller to a portrait mode only view controller it goes wrong - the portrait only view controllers gets presented in landscape.

Do you have any idea of how that can be made possible? Or maybe it requires a greater effort in ECSlidingViewController?

Thanks for a great product :)

Best regards,

Jens Schwarzer

**Comment by Eke** [comment]
was able to manage this using snippet bellow: 
- (BOOL)shouldAutorotate {
    return [self.topViewController shouldAutorotate];
}
