### ISSUE TITLE
UITableView swipe to delete conflicts with menu

### ISSUE THREAD

**Issue by richardsimko** [ECSlidingViewController/ECSlidingViewController#254]
Swipe to delete on UITableView followed by a press on a button to trigger the menu using `[self.slidingViewController anchorTopViewToRightAnimated:YES];` will cause the app to hang. However, swiping to deploy the menu won't. Here is a minimal project to test it: https://github.com/RichardSimko/ECSlidingViewControllerTest.

**Comment by dcacenabes** [comment]
Up. Happening again in iOS8

**Comment by MihaelIsaev** [comment]
Yeah, the same issue in iOS8

**Comment by aperechnev** [comment]
Any ideas how fix this?

**Comment by 0xPr0xy** [comment]
Up
