### ISSUE TITLE
Best way to toggle side menu to show / hide?

### ISSUE THREAD

**Issue by alexanderkent** [ECSlidingViewController/ECSlidingViewController#271]
I am using stoyboards and love how clean and easy it is to integrate. So I am using an UIBarButtonItem Menu button with an action to unwindToMenuViewController which shows the side menu when the user clicks that menu button. If the user clicks again on this button I would love to toggle the menu and hide the side menu. What’s the best way top do this? Should I implement 
- (IBAction)unwindToMenuViewController:(UIStoryboardSegue *)segue in my MenuViewController, how do I tell the menu to close?

**Comment by anuraagdjain** [comment]
Swift version 
`import ECSlidingViewController`

`if self.slidingViewController().currentTopViewPosition == ECSlidingViewControllerTopViewPosition.Centered{
            self.slidingViewController().anchorTopViewToRightAnimated(true)
        }else{
        self.slidingViewController().resetTopViewAnimated(true)
        }`
