### ISSUE TITLE
Missing topViewController

### ISSUE THREAD

**Issue by Leverin** [ECSlidingViewController/ECSlidingViewController#291]
Hi,

I'm getting an error saying "Missing topViewController', reason: 'Set the topViewController before loading ECSlidingViewController'". It explicitly says what the error is, but I don't know how to set the topViewController before loading ECSlidingViewController. Any idea what I might be doing wrong?

Here's the viewDidLoad code in my initController:
- (void)viewDidLoad
  {
  [super viewDidLoad];
  
  self.topViewController = [self.storyboard instantiateViewControllerWithIdentifier:@"myUIViewController"];
  }

Thanks in advance!

**Comment by sharathvatti** [comment]
Can't we do with out setting those key paths ? I want to set the topviewcontroller based on condition. Can u please help me.

Thanks in advance.
