### ISSUE TITLE
Got "Unbalanced calls to begin/end appearance transitions for UINavigationController" message

### ISSUE THREAD

**Issue by Jiera** [ECSlidingViewController/ECSlidingViewController#427]
Instead of using storyboard, I create underLeftViewController/underRightViewController at "viewWillAppear" and use "resetTopViewAnimated" after reseting topViewController at MENU page.

When I switch ViewController by MENU page on Simulator, Xcode output the message of "Unbalanced calls to begin/end appearance transitions for UINavigationController".

What does it mean, and how to fix it?

**Comment by gurtejsingh** [comment]
hi, I am getting the same error even when using a storyboard. Were you able to fix this at your end? Any help would be really appreciated! Thanks.

**Comment by gurtejsingh** [comment]
Any luck with this issue any one??? Please do help!

**Comment by yoha** [comment]
Refer to [How do I dispatch_sync, dispatch_async, dispatch_after, etc in Swift 3?](http://stackoverflow.com/questions/37801370/how-do-i-dispatch-sync-dispatch-async-dispatch-after-etc-in-swift-3)
